title: Hello, Tech HR
description: > # this means to ignore newlines until "baseurl:"
  I'd like to talk about HR management for Developers(I call it TechHR)
  Actually, I've worked as a developer for 10years. Now, I'm working in
  Developer Competency team(so weired) and I love to make the environment
  for developers.  
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andy Cho # add your name
author-img: andy.jpg # add your photo
about-author: I am an intrapreneur from SamsungSDS. # add description
twitter: namojo # add your Twitter handle
facebook: namojo # add your Facebook handle
github: namojo # add your Github handle
linkedin: 남호-조-46062756 # add your Linkedin handle
email: chonamho@gmail.com # add your Email address

# Disqus
discus-identifier: namojo # add your discus identifier

# Tracker
## analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

theme: jekyll-theme-minimal
